WIP: devspace sleep
nocalhost/nocalhost pull request #1100
Opened 2021-11-19 15:53 UTC by ovaldi

2021-11-25 13:32 UTC, lyzhang1999 requested changes

2021-11-25 13:32 UTC, lyzhang1999 commented on cmd/nocalhost-cron/jobs/sleep.go
> +	for _, cs := range clusters {
考虑用 go routine 处理，这里可能会出现的一个情况是 list 中的某一个集群超时，会导致其他任务阻塞。

2021-11-25 13:32 UTC, lyzhang1999 commented on cmd/nocalhost-cron/jobs/sleep.go
> +package jobs
定时任务能否用 informer 来监听“实时”状态

2021-11-25 13:32 UTC, lyzhang1999 commented on internal/nocalhost-api/sleep/utils.go
> +	// 2. purging Deployment
这里有两个疑问：
1. 对正在开发中的工作负载不进行缩容
2. 需要处理的工作负载类型有：Deployment、STS、DS、JOB、CRONJOB；以及不受控制器管控的 Pod

2021-11-25 13:32 UTC, lyzhang1999 commented on internal/nocalhost-api/sleep/utils.go
> +	// 3. restore StatefulSet
这里同理需要 wakeup：Deployment、STS、DS、JOB、CRONJOB；以及不受控制器管控的 Pod；

2021-11-25 13:34 UTC, lyzhang1999 commented
另外提交的时候缺少 DCO 签名，可以看到历史提交的 commit 是未通过的状态。

2021-11-25 13:55 UTC, ovaldi commented on cmd/nocalhost-cron/jobs/sleep.go
> +package jobs
是的，informer 监听的方案，在之前的迭代会的文档中有提到，主要是考虑一个重要的场景 informer 貌似无法处理：休眠/唤醒的依据是时间，当 devspace 达到休眠/唤醒要求，但 namespace 本身并不会有任何变化以触发通知？

2021-11-25 14:05 UTC, ovaldi commented on cmd/nocalhost-cron/jobs/sleep.go
> +	for _, cs := range clusters {
OK, updated, thank you :)

2021-11-25 14:24 UTC, lyzhang1999 commented on cmd/nocalhost-cron/jobs/sleep.go
> +package jobs
确实是，这里还是需要靠定时任务来处理。

2021-11-29 09:38 UTC, ovaldi commented on internal/nocalhost-api/sleep/utils.go
> +	// 2. purging Deployment
经会议讨论：
1. 工作负载增加 annotation 标识，用于识别进入开发模式
2. Job、CRD、DameonSet、静态 Pod：暂不处理

2021-11-29 09:38 UTC, ovaldi commented on internal/nocalhost-api/sleep/utils.go
> +	// 3. restore StatefulSet
经会议讨论：
1. 工作负载增加 annotation 标识，用于识别进入开发模式
2. Job、CRD、DameonSet、静态 Pod：暂不处理

2021-12-14 08:56 UTC, merged